name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Get current version
        id: version
        run: echo "::set-output name=version::$(git describe --tags --abbrev=0 || echo '0.0.0')"

      - name: Set specific tag for commit
        id: set-tag
        run: |
          CURRENT_VERSION=${{ steps.version.outputs.version }}
          NEW_VERSION=$(semver bump patch $CURRENT_VERSION)
          echo "Setting version $NEW_VERSION"
          echo "::set-output name=tag::$NEW_VERSION"
          docker tag hamidmusayev04/nummy-ui:latest hamidmusayev04/nummy-ui:$NEW_VERSION
          docker tag hamidmusayev04/nummy-api:latest hamidmusayev04/nummy-api:$NEW_VERSION

      - name: Build and push Docker UI image
        run: |
          NEW_VERSION=${{ steps.set-tag.outputs.tag }}
          docker build -t hamidmusayev04/nummy-ui:$NEW_VERSION -t hamidmusayev04/nummy-ui:latest .
          docker push hamidmusayev04/nummy-ui:latest
          docker push hamidmusayev04/nummy-ui:$NEW_VERSION

      - name: Build and push Docker API image
        run: |
          NEW_VERSION=${{ steps.set-tag.outputs.tag }}
          docker build -t hamidmusayev04/nummy-api:$NEW_VERSION -t hamidmusayev04/nummy-api:latest .
          docker push hamidmusayev04/nummy-api:latest
          docker push hamidmusayev04/nummy-api:$NEW_VERSION

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
